# Generated by Django 5.1.6 on 2025-03-14 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNo', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('addharNo', models.CharField(max_length=20, unique=True)),
                ('dOB', models.DateField()),
                ('designation', models.CharField(choices=[('Team Leader', 'Team Leader'), ('Project Manager', 'Project Manager'), ('Senior Developer', 'Senior Developer'), ('Junior Developer', 'Junior Developer'), ('Intern', 'Intern'), ('QA Tester', 'QA Tester')], max_length=50)),
                ('salary', models.CharField(max_length=20)),
                ('joinDate', models.DateField()),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employee.department')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=50)),
                ('days', models.PositiveSmallIntegerField()),
                ('eId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('publishDate', models.DateTimeField()),
                ('departments', models.ManyToManyField(blank=True, related_name='notices', to='employee.department')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('requestMessage', models.TextField()),
                ('requestDate', models.DateTimeField()),
                ('destinationEmployeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toEmployeeId', to='employee.employee')),
                ('requesterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requesterId', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkAssignments',
            fields=[
                ('Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('work', models.TextField()),
                ('assignDate', models.DateTimeField()),
                ('dueDate', models.DateTimeField()),
                ('assignerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignerId', to='employee.employee')),
                ('taskerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskerId', to='employee.employee')),
            ],
        ),
    ]
