# Generated by Django 5.1.6 on 2025-04-01 05:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('eID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNo', models.CharField(max_length=12, unique=True)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('addharNo', models.CharField(max_length=20, unique=True)),
                ('dOB', models.DateField()),
                ('designation', models.CharField(choices=[('Team Leader', 'Team Leader'), ('Project Manager', 'Project Manager'), ('Senior Developer', 'Senior Developer'), ('Junior Developer', 'Junior Developer'), ('Intern', 'Intern'), ('QA Tester', 'QA Tester'), ('HR', 'HR')], max_length=50)),
                ('salary', models.CharField(max_length=20)),
                ('joinDate', models.DateField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('hr', 'HR'), ('manager', 'Manager'), ('employee', 'Employee')], default='employee', max_length=20)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='employee.department')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('publishDate', models.DateTimeField()),
                ('departments', models.ManyToManyField(blank=True, related_name='notices', to='employee.department')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('resource', 'Resource Request'), ('support', 'Support Request'), ('approval', 'Approval Request'), ('other', 'Other')], default='other', max_length=20)),
                ('request_message', models.TextField()),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to='employee.employee')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkAssignments',
            fields=[
                ('Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('work', models.TextField()),
                ('assignDate', models.DateTimeField()),
                ('dueDate', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('progress_report', models.TextField(blank=True, null=True)),
                ('progress_file', models.FileField(blank=True, null=True, upload_to='work_files/')),
                ('manager_feedback', models.TextField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20)),
                ('assignerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_works', to='employee.employee')),
                ('taskerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkAssignmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
                ('work_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='employee.workassignments')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave')], default='present', max_length=10)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('check_in_latitude', models.FloatField(blank=True, null=True)),
                ('check_in_longitude', models.FloatField(blank=True, null=True)),
                ('check_out_latitude', models.FloatField(blank=True, null=True)),
                ('check_out_longitude', models.FloatField(blank=True, null=True)),
                ('eId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='employee.employee')),
            ],
            options={
                'unique_together': {('eId', 'date')},
            },
        ),
    ]
