# Generated by Django 5.1.6 on 2025-04-02 16:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('Id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('request_message', models.TextField()),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests_received', to='employee.employee')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests_made', to='employee.employee')),
            ],
        ),
    ]
