# Generated by Django 5.1.6 on 2025-04-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_notification_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='request_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
