# Generated by Django 5.1.6 on 2025-04-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_notice_expires_on_notice_is_active_notice_is_urgent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
