# Generated by Django 5.1.6 on 2025-04-11 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auditlog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='can_assign_cross_department',
            field=models.BooleanField(default=False, help_text='Indicates whether this employee can assign tasks to employees in other departments.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='addharNo',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhar number must be exactly 12 digits.')]),
        ),
    ]
