# Generated by Django 5.1.6 on 2025-04-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_employee_can_assign_cross_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='addharNo',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
