# Generated by Django 5.1.6 on 2025-04-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_employee_addharno'),
    ]

    operations = [
        migrations.AddField(
            model_name='workassignments',
            name='feedback_satisfactory',
            field=models.BooleanField(default=False),
        ),
    ]
