# Generated by Django 5.1.6 on 2025-04-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_workassignments_feedback_satisfactory'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='is_compulsory',
            field=models.BooleanField(default=False),
        ),
    ]
