# Generated by Django 5.1.6 on 2025-04-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_leaverequest_is_compulsory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the employee was archived.', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Indicates whether the employee's account is active. Deactivated accounts cannot log in."),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Indicates whether the employee is archived (e.g., resigned).'),
        ),
    ]
