# Generated by Django 5.1.6 on 2025-04-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_employee_archived_at_employee_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='feedback',
            field=models.TextField(blank=True, help_text='Feedback from the recipient.', null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Indicates if the requester has locked the request after being satisfied with the feedback.'),
        ),
        migrations.AddField(
            model_name='requests',
            name='request_file',
            field=models.FileField(blank=True, help_text='Optional file attachment for the request.', null=True, upload_to='request_files/'),
        ),
    ]
