# Generated by Django 5.1.6 on 2025-04-15 12:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0018_employee_has_completed_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('id_card', 'ID Card'), ('certificate', 'Certificate'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(help_text='Allowed formats: PDF, JPG, JPEG, PNG, DOC, DOCX', upload_to='employee_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Mark as sensitive to restrict access to HR/Admins only.')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relationship', models.CharField(help_text='e.g., Parent, Spouse, Friend', max_length=50)),
                ('phone_no', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,12}$', "Phone number must be 10-12 digits, optionally starting with a '+'.")])),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('salary', models.CharField(blank=True, max_length=20, null=True)),
                ('reason_for_change', models.TextField(blank=True, help_text='e.g., Promotion, Transfer', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_history', to='employee.employee')),
            ],
        ),
    ]
