# Generated by Django 5.1.6 on 2025-04-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_document_emergencycontact_jobhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobHistory',
        ),
    ]
