# Generated by Django 5.1.6 on 2025-04-15 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_performancereviewtemplate_performancereview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_name', models.CharField(max_length=50)),
                ('fields', models.JSONField()),
                ('filters', models.JSONField()),
                ('aggregation', models.CharField(blank=True, max_length=20, null=True)),
                ('aggregation_field', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to='employee.employee')),
            ],
        ),
    ]
