# Generated by Django 5.1.6 on 2025-04-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_savedreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedReport',
        ),
    ]
