# Generated by Django 5.1.6 on 2025-05-08 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_alter_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_latitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_longitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_latitude',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_longitude',
        ),
    ]
