# Generated by Django 5.1.6 on 2025-05-08 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0029_remove_attendance_check_in_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewquestion',
            options={},
        ),
        migrations.RemoveField(
            model_name='reviewquestion',
            name='order',
        ),
    ]
